"""empty message

Revision ID: 407f01ec7310
Revises: 
Create Date: 2020-05-03 23:41:44.194705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407f01ec7310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('stain', sa.String(), nullable=True),
    sa.Column('accession_number', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('contributor', sa.String(), nullable=True),
    sa.Column('processing', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('date_collected', sa.String(), nullable=True),
    sa.Column('date_received', sa.String(), nullable=True),
    sa.Column('date_sent_to_aperio', sa.String(), nullable=True),
    sa.Column('sample', sa.String(), nullable=True),
    sa.Column('infect', sa.String(), nullable=True),
    sa.Column('study', sa.String(), nullable=True),
    sa.Column('collection_site', sa.String(), nullable=True),
    sa.Column('histopathologic_description', sa.String(), nullable=True),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_slides')
    op.drop_table('lessons')
    op.drop_table('auth')
    op.drop_table('users')
    op.drop_table('slides')
    op.drop_table('courses')
    op.drop_table('annotations')
    # ### end Alembic commands ###
