"""empty message

Revision ID: 4b82e0c17666
Revises: 407f01ec7310
Create Date: 2020-05-06 02:25:24.939049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b82e0c17666'
down_revision = '407f01ec7310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('lesson_slides', sa.Column('description', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'description')
    op.drop_column('lesson_slides', 'description')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
